name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        path: vlink
        
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7'

    - name: Build the app
      working-directory: vlink
      run: |
        dotnet publish VLink.Private.GrpcRoomServer.csproj -c Release -o ../app /p:UseAppHost=false
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vlink-server-room:$(date +%s)
